version: 2.1
orbs:
  node: circleci/node@4.7.0
  coveralls: coveralls/coveralls@1.0.5
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest-browsers
    
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test
      - run: npm run coverage
      - run:
          name: Set environment variables
          command: echo ${TEST_DB_USERNAME}
      
workflows:
  version: 2.1
  build:
    jobs:
      - build-and-test
  
notify: 
  webhooks: 
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}